version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    container_name: project-x27-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./logs/frontend:/usr/src/app/logs
      - ./frontend-next:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3000
    networks:
      - project-x27-network
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project-x27-backend
    ports:
      - "3000:3000"
    volumes:
      - ./logs/backend:/usr/src/app/logs
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - project-x27-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  project-x27-network:
    driver: bridge
